AllCops:
  Exclude:
    - 'pageobjects/**/**/*'
    - 'library/**/*'q
    - 'features/step_definitions/ui/**/*'
    - 'features/step_definitions/ui/**/**/*'
    - 'features/step_definitions/service/*'
    - 'service/db_service.rb'
Metrics/ClassLength:
  Max: 250
Metrics/BlockLength:
  Max: 50
