inherit_from:
  - .robocop_add_rules.yml

inherit_mode:
 merge:
  - Exclude

Style/For:
  inherit_mode:
  override:
    - Exclude
  Exclude:
    - 'service/db_service.rb'
    - 'page_objects/dashboard_alert_page.rb'

AllCops:
  Exclude:
    - 'pageobjects/**/**/*'
    - 'library/**/*'
    - 'features/step_definitions/ui/**/*'
    - 'features/step_definitions/ui/**/**/*'
    - 'features/step_definitions/service/*'
Metrics/ClassLength:
  Max: 250
Metrics/BlockLength:
  Max: 50

