# frozen_string_literal: true
source 'https://rubygems.org'

gem 'appium_lib', '11.2.0'
gem 'cucumber', '3.1.2'
gem 'facets'
gem 'httparty'
gem 'json-schema'
gem 'liquid'
gem 'logger'
gem 'os'
gem 'page-object', '2.2.6'
gem 'pg'
gem 'rake'
gem 'require_all', '~> 1.4.0'
gem 'rest-client', '2.1.0'
gem 'rspec', require: 'spec'
gem 'rufo'
gem 'screenshot'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'solargraph'
