# frozen_string_literal: true

source 'https://rubygems.org'

gem 'appium_lib'
gem 'cucumber', '7.1.0'
gem 'facets'
gem 'httparty'
gem 'json-schema'
gem 'liquid'
gem 'logger'
gem 'os'
gem 'page-object'
gem 'pg'
gem 'rake'
gem 'require_all', '~> 1.4.0'
gem 'rest-client', '2.1.0'
gem 'rspec', require: 'spec'
gem 'rufo'
gem 'screenshot'
gem 'selenium-webdriver', '4.0.3'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'solargraph'
gem 'spreadsheet'
