@lng-section-4b
Feature: LNGSmartFormsPermission
    As a ...
    I want to ...
    So that ...

    Scenario: EIC certification section 4b competent person label change to C/O 2/E

    Scenario: EIC certification section 4b issuing authority to change to Master and C/E