dashboard_chrome:
  platformName: "Android"
  platformVersion: "7.1"
  deviceName: "201902230863"
  app: ""
  port: 4723
  browserName: "Chrome"
  isHeadless: true
  noReset: false

tablet_chrome:
  platformName: "Android"
  platformVersion: "8.1"
  deviceName: "4aa590af"
  app: ""
  port: 4723
  browserName: "Chrome"
  isHeadless: true
  noReset: false

ue_tablet_a_chrome:
  platformName: "Android"
  platformVersion: "8.1"
  deviceName: "10.100.1.97:5555"
  app: ""
  port: 8200
  browserName: "Chrome"
  isHeadless: true
  noReset: false

ue_tablet_b_chrome:
  platformName: "Android"
  platformVersion: "8.1"
  deviceName: "10.100.1.2:5555"
  app: ""
  port: 8201
  browserName: "Chrome"
  isHeadless: true
  noReset: false

ue_dashboard_chrome:
  platformName: "Android"
  platformVersion: "7.1"
  deviceName: "10.100.1.95:5555"
  app: ""
  port: 8202
  browserName: "Chrome"
  isHeadless: true
  noReset: false

thinktouch_android_ue_dashboard_chrome:
  platformName: "Android"
  platformVersion: "9.1"
  deviceName: "10.100.1.72:5555"
  app: ""
  port: 8201
  browserName: "Chrome"
  isHeadless: true
  noReset: false
