dashboard_chrome:
  platformName: "Android"
  platformVersion: "7.1"
  deviceName: "201902230863"
  port: 4723
  browserName: "Chrome"
  isHeadless: true
  noReset: false

tablet_chrome:
  platformName: "Android"
  platformVersion: "8.1"
  deviceName: "4aa590af"
  port: 8200
  browserName: "Chrome"
  chromedriverPort: 9515
  appiumPort: 4723
  isHeadless: true
  noReset: false

ue_tablet_a_chrome:
  platformName: "Android"
  platformVersion: "8.1"
  deviceName: "6572e096"
  port: 8200
  udid: "6572e096"
  browserName: "Chrome"
  chromedriverPort: 9515
  adbPort: 5037
  appiumPort: 4723
  isHeadless: true
  noReset: false

ue_tablet_b_chrome:
  platformName: "Android"
  platformVersion: "8.1"
  deviceName: "409f97da"
  udid: "409f97da"
  port: 8201
  browserName: "Chrome"
  chromedriverPort: 9516
  adbPort: 5038
  appiumPort: 4724
  isHeadless: true
  noReset: false

ue_dashboard_chrome:
  platformName: "Android"
  platformVersion: "7.1"
  deviceName: "202092300E49"
  udid: "202092300E49"
  port: 8202
  browserName: "Chrome"
  chromedriverPort: 9517
  adbPort: 5039
  appiumPort: 4725
  isHeadless: true
  noReset: false

thinktouch_android_ue_dashboard_chrome:
  platformName: "Android"
  platformVersion: "9.1"
  deviceName: "10.100.1.72:5555"
  port: 8201
  browserName: "Chrome"
  isHeadless: true
  noReset: false
