##Service
dev:
  c2_preview: "http://cloud-edge.dev.solas.magellanx.io:8080"
  service: "http://cloud-edge.dev.solas.magellanx.io:4000/"

sit:
  c2_preview: "http://cloud-edge.stage.solas.magellanx.io:8080"
  # c2_preview: "https://52.230.70.68:8443"
  service: "http://cloud-edge.stage.solas.magellanx.io:4000/"

sits:
  c2_preview: "https://cloud-edge.stage.solas.magellanx.io:8443/"
  service: "http://cloud-edge.stage.solas.magellanx.io:4000/"

uat:
  c2_preview: "http://104.215.192.113:8080"
  service: "http://104.215.192.11:4000"

sit_fauxton_forms:
  delete_form: "http://52.230.70.68:5984/forms/_bulk_docs"
  get_forms: "http://52.230.70.68:5984/forms/_all_docs?skip=0&limit=10000"
  get_user: "http://52.230.70.68:5984/users/_all_docs?skip=0&limit=1000"
  delete_user: "http://52.230.70.68:5984/users/_bulk_docs"

jira_url: "https://teamsolas.atlassian.net/browse/"

## To enable and disable screenshot feature ##
# "True" - Takes screenshot for all steps ##
# "False" - Takes screenshot only for failures ##
screenshot: "true"
