---
sit:
  c2_preview: https://%s.edge.dev.safevue.ai:8080/
  fauxton_url: https://admin:magellanx@%s.edge.dev.safevue.ai:5984/
  service: https://%s.edge.dev.safevue.ai:4000/
  switch_vessel: https://admin:magellanx@%s.edge.dev.safevue.ai:5984/vessels/sit-vessel
uat:
  c2_preview: https://uat.edge.dev.safevue.ai:8080/
  fauxton_url: https://admin:magellanx@uat.edge.dev.safevue.ai:5984/
  service: https://uat.edge.dev.safevue.ai:4000/
auto:
  c2_preview: https://%s.edge.dev.safevue.ai:8080/
  fauxton_url: https://admin:magellanx@%s.edge.dev.safevue.ai:5984/
  service: https://%s.edge.dev.safevue.ai:4000/
  switch_vessel: https://admin:magellanx@%s.edge.dev.safevue.ai:5984/vessels/auto-vessel
edge:
  add-work-rest-hour: work_rest_hour/_bulk_docs
  delete_alerts_histories_entries: alerts/_bulk_docs
  delete_form: forms/_bulk_docs
  delete_gas_entries: gas_reader_entry/_bulk_docs
  delete_geofence: geofence/_bulk_docs
  delete_user: users/_bulk_docs
  # delete_wearable_active_users: wearables_active_users/_bulk_docs
  delete_wearable_histories_entries: wearables_history/_bulk_docs
  get_alerts_histories: alerts/_all_docs?include_docs=true&skip=0&limit=10000
  get_forms: forms/_all_docs?skip=0&limit=10000
  get_gas_reader_entries: gas_reader_entry/_all_docs?skip=0&limit=10000
  get_geofence: geofence/_all_docs?include_docs=true&skip=0&limit=10000
  get_pre_gas_entry_log: gas_reader_entry/%s
  get_user: users/_all_docs?skip=0&limit=1000
  get_wearable_histories: wearables_history/_all_docs?include_docs=true&skip=0&limit=10000
  get_workrest: work_rest_hour/_all_docs?skip=0&limit=10000
jira_url: https://teamsolas.atlassian.net/browse/
cloud:
  base_cloud_url: https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb.aks.dev.safevue.ai
  delete_forms: /forms/_bulk_docs
  delete_gas_entries: /gas_reader_entry/_bulk_docs
  delete_oa_event: /office_approval_events/_bulk_docs
  get_forms: /forms/_all_docs?skip=0&limit=10000
  get_gas_reader_entries: /gas_reader_entry/_all_docs?skip=0&limit=10000
  get_oa_event: /office_approval_events/_all_docs?include_docs=true&skip=0&limit=10000
  get_crew_members: /crew_members/_find
  set_crew_members: /crew_members/_bulk_docs
office_approval:
  format_link: https://office.dev.safevue.ai/permit-preview/%s?formId=%s&staffId=%s
  get_event_id: https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb.aks.dev.safevue.ai/office_approval_events/_find
  get_form_status: https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb.aks.dev.safevue.ai/forms/_find
  get_staff_id: https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb.aks.dev.safevue.ai/office_staff/_find
  office_portal: https://office.dev.safevue.ai/login/demo-uid
  office_portal_permit_view: https://office.dev.safevue.ai/permit-overview?formId=%s
  password: 13-dead-CENT-think-56
postgres:
  safevue:
    database: safevue
    host: safevue-dev.postgres.database.azure.com
    password: 79-window-CHOOSE-nation-38
    username: safevue_user@safevue-dev
  dataiku:
    database: dataiku
    host: safevue-dev.postgres.database.azure.com
    password: 41-pass-STREAM-deep-36
    username: safevue_dataiku@safevue-dev
screenshot: 'true'
