##Service
dev:
  c2_preview: "https://cloud-edge.dev.solas.magellanx.io:8080"
  service: "http://cloud-edge.dev.solas.magellanx.io:4000/"
  master_pin: "9707"

sit:
  c2_preview: "https://cloud-edge.stage.solas.magellanx.io:8080"
  service: "https://cloud-edge.stage.solas.magellanx.io:4000/"
  master_pin: "1111"

sits:
  c2_preview: "https://cloud-edge.stage.solas.magellanx.io:8443/"
  service: "https://cloud-edge.stage.solas.magellanx.io:4000/"
  master_pin:

auto:
  c2_preview: "https://cloud-edge.auto.solas.magellanx.io:8080/"
  service: "https://cloud-edge.auto.solas.magellanx.io:4000/"
  master_pin: "1111"

uat:
  c2_preview: "http://104.215.192.113:8080"
  service: "http://104.215.192.113:4000"
  master_pin:

fauxton:
  base_auto_url: "https://admin:magellanx@cloud-edge.auto.solas.magellanx.io:5984"
  base_sit_url: "https://admin:magellanx@cloud-edge.stage.solas.magellanx.io:5984"
  base_dev_url: "https://admin:magellanx@23.97.50.121:5984"
  delete_form: "/forms/_bulk_docs"
  delete_gas_entries: "/gas_reader_entry/_bulk_docs"
  delete_wearable_histories_entries: "/wearables_history/_bulk_docs"
  delete_wearable_active_users: "/wearables_active_users/_bulk_docs"
  get_forms: "/forms/_all_docs?skip=0&limit=10000"
  get_user: "/users/_all_docs?skip=0&limit=1000"
  get_pre_gas_entry_log: "/gas_reader_entry/%s"
  delete_user: "/users/_bulk_docs"
  get_gas_reader_entries: "/gas_reader_entry/_all_docs?skip=0&limit=10000"
  get_wearable_histories: "/wearables_history/_all_docs?skip=0&limit=10000"
  get_wearable_active_users: "/wearables_active_users/_all_docs?skip=0&limit=10000"

oa_db:
  base_sit_url: "https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb.dev.solas.magellanx.io"
  base_dev_url: "https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb.dev.solas.magellanx.io"
  delete_oa_event: "/office_approval_events/_bulk_docs"
  delete_gas_entries: "/gas_reader_entry/_bulk_docs"
  get_oa_event: "/office_approval_events/_all_docs?skip=0&limit=10000"
  get_gas_reader_entries: "/gas_reader_entry/_all_docs?skip=0&limit=10000"

ldev_fauxton_forms:
  delete_form: "http://sandbox-admin:magellanx@d0b02eada7fb.ngrok.io/forms/_bulk_docs"
  get_forms: "http://sandbox-admin:magellanx@d0b02eada7fb.ngrok.io/forms/_all_docs?skip=0&limit=10000"

jira_url: "https://teamsolas.atlassian.net/browse/"

office_approval:
  format_link: "http://solas-dev-office-portal.azurewebsites.net/permit-preview/%s?formId=%s&staffId=%s"
  office_portal: "http://solas-dev-office-portal.azurewebsites.net/login/demo-uid"
  get_event_id: "https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb.dev.solas.magellanx.io/office_approval_events/_find"
  get_staff_id: "https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb.dev.solas.magellanx.io/office_staff/_find"
  password: "13-dead-CENT-think-56"

maria_db:
  mariadb_host: "safevue-mariadb-dev.mariadb.database.azure.com"
  mariadb_user: "safevue@safevue-mariadb-dev"
  mariadb_pass: "64d58dba2c535612841489d69a4d9998"
  Emariadb_database: "replication"

pin_management:
  sit:
    db: "https://admin:magellanx@cloud-edge.stage.solas.magellanx.io:5984/"
    vessel: "sit-vessel"
  dev:

## To enable and disable screenshot feature ##
# "True" - Takes screenshot for all steps ##
# "False" - Takes screenshot only for failures ##
screenshot: "true"
