##Service
dev:
  c2_preview: "https://dev.edge.dev.safevue.ai:8080"
  service: "http://dev.edge.dev.safevue.ai:4000/"
  fauxton_url: "https://admin:magellanx@dev.edge.dev.safevue.ai:5984"

sit:
  c2_preview: "https://sit.edge.dev.safevue.ai:8080"
  service: "https://sit.edge.dev.safevue.ai:4000/"
  master_pin: "1111"
  switch_vessel: "https://admin:magellanx@sit.edge.dev.safevue.ai:5984/vessels/sit-lng-vessel"
  update_mas_pin: "https://admin:magellanx@sit.edge.dev.safevue.ai:5984/users/SIT_SOLX0001"
  get_crew_members: "https://admin:magellanx@sit.edge.dev.safevue.ai:5984/crew_members/_find"
  fauxton_url: "https://admin:magellanx@sit.edge.dev.safevue.ai:5984"

auto:
  c2_preview: "https://auto.edge.dev.safevue.ai:8080/"
  service: "https://auto.edge.dev.safevue.ai:4000/"
  master_pin: "1111"
  update_mas_pin: "https://admin:magellanx@auto.edge.dev.safevue.ai:5984/users/AUTO_SOLX0001"
  switch_vessel: "https://admin:magellanx@auto.edge.dev.safevue.ai:5984/vessels/auto-vessel"
  get_crew_members: "https://admin:magellanx@auto.edge.dev.safevue.ai:5984/crew_members/_find"
  fauxton_url: "https://admin:magellanx@auto.edge.dev.safevue.ai:5984"

uat:
  c2_preview: "https://uat.edge.dev.safevue.ai:8080/"
  service: "https://uat.edge.dev.safevue.ai:4000/"
  fauxton_url: "https://admin:magellanx@uat.edge.dev.safevue.ai:5984"
  get_crew_members: "https://admin:magellanx@uat.edge.dev.safevue.ai:5984/crew_members/_find"

fauxton:
  base_uat_url: "https://admin:magellanx@uat.edge.dev.safevue.ai:5984"
  base_auto_url: "https://admin:magellanx@auto.edge.dev.safevue.ai:5984"
  base_sit_url: "https://admin:magellanx@sit.edge.dev.safevue.ai:5984"
  base_dev_url: "https://admin:magellanx@dev.edge.dev.safevue.ai:5984"
  delete_form: "/forms/_bulk_docs"
  delete_gas_entries: "/gas_reader_entry/_bulk_docs"
  delete_wearable_histories_entries: "/wearables_history/_bulk_docs"
  delete_wearable_active_users: "/wearables_active_users/_bulk_docs"
  get_forms: "/forms/_all_docs?skip=0&limit=10000"
  get_workrest: "/work_rest_hour/_all_docs?skip=0&limit=10000"
  get_user: "/users/_all_docs?skip=0&limit=1000"
  get_pre_gas_entry_log: "/gas_reader_entry/%s"
  delete_user: "/users/_bulk_docs"
  add-work-rest-hour: "/work_rest_hour/_bulk_docs"
  get_gas_reader_entries: "/gas_reader_entry/_all_docs?skip=0&limit=10000"
  get_wearable_histories: "/wearables_history/_all_docs?skip=0&limit=10000"
  get_wearable_active_users: "/wearables_active_users/_all_docs?skip=0&limit=10000"

oa_db:
  base_uat_url: "https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb.dev.solas.magellanx.io"
  base_sit_url: "https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb.dev.solas.magellanx.io"
  base_dev_url: "https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb.dev.solas.magellanx.io"
  delete_oa_event: "/office_approval_events/_bulk_docs"
  delete_gas_entries: "/gas_reader_entry/_bulk_docs"
  get_oa_event: "/office_approval_events/_all_docs?skip=0&limit=10000"
  get_gas_reader_entries: "/gas_reader_entry/_all_docs?skip=0&limit=10000"

jira_url: "https://teamsolas.atlassian.net/browse/"

office_approval:
  format_link: "https://office.dev.safevue.ai/permit-preview/%s?formId=%s&staffId=%s"
  office_portal: "https://office.dev.safevue.ai/login/demo-uid"
  get_event_id: "https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb.dev.solas.magellanx.io/office_approval_events/_find"
  get_staff_id: "https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb.dev.solas.magellanx.io/office_staff/_find"
  password: "13-dead-CENT-think-56"

# maria_db:
#   mariadb_host: "safevue-mariadb-dev.mariadb.database.azure.com"
#   mariadb_user: "safevue@safevue-mariadb-dev"
#   mariadb_pass: "64d58dba2c535612841489d69a4d9998"
#   Emariadb_database: "replication"

postgres:
  adapter: "postgresql"
  encoding: "unicode"
  database: "safevue"
  pool: 5
  username: "safevue_user@safevue-dev"
  password: "79-window-CHOOSE-nation-38"
  host: "safevue-dev.postgres.database.azure.com"

pin_management:
  sit:
    db: "https://admin:magellanx@sit.edge.dev.safevue.ai:5984/"
    vessel: "sit-vessel"
  dev:

## To enable and disable screenshot feature ##
# "True" - Takes screenshot for all steps ##
# "False" - Takes screenshot only for failures ##
screenshot: "true"
