---
edge:
  add-work-rest-hour: work_rest_hour/_bulk_docs
  get_pre_gas_entry_log: gas_reader_entry/%s
  get_user: users/_all_docs?skip=0&limit=1000
  get_workrest: work_rest_hour/_all_docs?skip=0&limit=10000
jira_url: https://teamsolas.atlassian.net/browse/
cloud:
  base_cloud_url: https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb-sit.cloud.solx.safevue.ai
  get_crew_members: /crew_members/_find
  set_crew_members: /crew_members/_bulk_docs
office_approval:
  format_link: https://office-sit.cloud.solx.safevue.ai/permit-preview/%s?formId=%s&staffId=%s
  get_event_id: https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb-sit.cloud.solx.safevue.ai/office_approval_events/_find
  get_form_status: https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb-sit.cloud.solx.safevue.ai/forms/_find
  get_staff_id: https://admin:gkmQjrP6Lmsd1tvZLTez@couchdb-sit.cloud.solx.safevue.ai/office_staff/_find
  office_portal: https://office-sit.cloud.solx.safevue.ai/
  office_portal_permit_view: https://office-sit.cloud.solx.safevue.ai/permit-overview?formId=%s
  password: Solxtester12345!
postgres:
  safevue:
    database: safevue_sit
    host: safevue-solx.postgres.database.azure.com
    password: 79-window-CHOOSE-nation-38
    username: write_user@safevue-solx
  reporting:
    database: reporting_sit
    host: safevue-solx.postgres.database.azure.com
    password: 10-joined-TEAR-greek-36
    username: reporting_user@safevue-solx
screenshot: 'true'
