##Service
dev:
  c2_preview: "http://cloud-edge.dev.solas.magellanx.io:8080/dashboard"
  service: "http://23.97.50.121:4000"

sit:
  c2_preview: "http://cloud-edge.stage.solas.magellanx.io:8080/dashboard"
  service: "http://52.230.70.68:4000"

uat:
  c2_preview: "http://104.215.192.113:8080"
  service: "http://104.215.192.11:4000"

jira_url: "https://teamsolas.atlassian.net/browse/"

## To enable and disable screenshot feature ##
# "True" - Takes screenshot for all steps ##
# "False" - Takes screenshot only for failures ##
screenshot: "true"
