@section3CDRA
Feature: Section3CDRA
  As a ...
  I want to ...
  So that ...

  Scenario: [Section 3c] - Verify user can select multiple DRA members
  Scenario: [Section 3c] - Verify user can unselect all DRA team member
  Scenario: [Section 3c] - Verify user can remove specific DRA team member