@bypass-section6
Feature: To bypass section 1 to 6
  As a ...
  I want to ...
  So that ...

  Scenario: To bypass section 6 for permit that don't requires gas reader update
    Given I trigger to bypass section6 via service with 1212 user